#ifndef __macro_utils__
#define __macro_utils__

#define ADD(ins, ...) add(#ins, ins, ##__VA_ARGS__)
#define SET(ins, ...) set(#ins, ins, ##__VA_ARGS__)
#define LOG(ins, ...) log(#ins, ins, ##__VA_ARGS__)
#define TRIGGER(ins, ...) trigger(#ins, ins, ##__VA_ARGS__)

#define Pairz(ins)                                                                                                                                             \
    { #ins, ins }

#define Pairs_1(ins, ...) Pairz(ins)
#define Pairs_2(ins, ...) Pairz(ins), Pairs_1(__VA_ARGS__)
#define Pairs_3(ins, ...) Pairz(ins), Pairs_2(__VA_ARGS__)
#define Pairs_4(ins, ...) Pairz(ins), Pairs_3(__VA_ARGS__)
#define Pairs_5(ins, ...) Pairz(ins), Pairs_4(__VA_ARGS__)
#define Pairs_6(ins, ...) Pairz(ins), Pairs_5(__VA_ARGS__)
#define Pairs_7(ins, ...) Pairz(ins), Pairs_6(__VA_ARGS__)
#define Pairs_8(ins, ...) Pairz(ins), Pairs_7(__VA_ARGS__)
#define Pairs_9(ins, ...) Pairz(ins), Pairs_8(__VA_ARGS__)
#define Pairs_10(ins, ...) Pairz(ins), Pairs_9(__VA_ARGS__)
#define Pairs_11(ins, ...) Pairz(ins), Pairs_10(__VA_ARGS__)
#define Pairs_12(ins, ...) Pairz(ins), Pairs_11(__VA_ARGS__)
#define Pairs_13(ins, ...) Pairz(ins), Pairs_12(__VA_ARGS__)
#define Pairs_14(ins, ...) Pairz(ins), Pairs_13(__VA_ARGS__)
#define Pairs_15(ins, ...) Pairz(ins), Pairs_14(__VA_ARGS__)
#define Pairs_16(ins, ...) Pairz(ins), Pairs_15(__VA_ARGS__)
#define Pairs_17(ins, ...) Pairz(ins), Pairs_16(__VA_ARGS__)
#define Pairs_18(ins, ...) Pairz(ins), Pairs_17(__VA_ARGS__)
#define Pairs_19(ins, ...) Pairz(ins), Pairs_18(__VA_ARGS__)
#define Pairs_20(ins, ...) Pairz(ins), Pairs_19(__VA_ARGS__)
#define Pairs_21(ins, ...) Pairz(ins), Pairs_20(__VA_ARGS__)
#define Pairs_22(ins, ...) Pairz(ins), Pairs_21(__VA_ARGS__)
#define Pairs_23(ins, ...) Pairz(ins), Pairs_22(__VA_ARGS__)
#define Pairs_24(ins, ...) Pairz(ins), Pairs_23(__VA_ARGS__)
#define Pairs_25(ins, ...) Pairz(ins), Pairs_24(__VA_ARGS__)
#define Pairs_26(ins, ...) Pairz(ins), Pairs_25(__VA_ARGS__)
#define Pairs_27(ins, ...) Pairz(ins), Pairs_26(__VA_ARGS__)
#define Pairs_28(ins, ...) Pairz(ins), Pairs_27(__VA_ARGS__)
#define Pairs_29(ins, ...) Pairz(ins), Pairs_28(__VA_ARGS__)
#define Pairs_30(ins, ...) Pairz(ins), Pairs_29(__VA_ARGS__)
#define Pairs_31(ins, ...) Pairz(ins), Pairs_30(__VA_ARGS__)
#define Pairs_32(ins, ...) Pairz(ins), Pairs_31(__VA_ARGS__)
#define Pairs_33(ins, ...) Pairz(ins), Pairs_32(__VA_ARGS__)
#define Pairs_34(ins, ...) Pairz(ins), Pairs_33(__VA_ARGS__)
#define Pairs_35(ins, ...) Pairz(ins), Pairs_34(__VA_ARGS__)
#define Pairs_36(ins, ...) Pairz(ins), Pairs_35(__VA_ARGS__)
#define Pairs_37(ins, ...) Pairz(ins), Pairs_36(__VA_ARGS__)
#define Pairs_38(ins, ...) Pairz(ins), Pairs_37(__VA_ARGS__)
#define Pairs_39(ins, ...) Pairz(ins), Pairs_38(__VA_ARGS__)
#define Pairs_40(ins, ...) Pairz(ins), Pairs_39(__VA_ARGS__)
#define Pairs_41(ins, ...) Pairz(ins), Pairs_40(__VA_ARGS__)
#define Pairs_42(ins, ...) Pairz(ins), Pairs_41(__VA_ARGS__)
#define Pairs_43(ins, ...) Pairz(ins), Pairs_42(__VA_ARGS__)
#define Pairs_44(ins, ...) Pairz(ins), Pairs_43(__VA_ARGS__)
#define Pairs_45(ins, ...) Pairz(ins), Pairs_44(__VA_ARGS__)
#define Pairs_46(ins, ...) Pairz(ins), Pairs_45(__VA_ARGS__)
#define Pairs_47(ins, ...) Pairz(ins), Pairs_46(__VA_ARGS__)
#define Pairs_48(ins, ...) Pairz(ins), Pairs_47(__VA_ARGS__)
#define Pairs_49(ins, ...) Pairz(ins), Pairs_48(__VA_ARGS__)
#define Pairs_50(ins, ...) Pairz(ins), Pairs_49(__VA_ARGS__)
#define Pairs_51(ins, ...) Pairz(ins), Pairs_50(__VA_ARGS__)
#define Pairs_52(ins, ...) Pairz(ins), Pairs_51(__VA_ARGS__)
#define Pairs_53(ins, ...) Pairz(ins), Pairs_52(__VA_ARGS__)
#define Pairs_54(ins, ...) Pairz(ins), Pairs_53(__VA_ARGS__)
#define Pairs_55(ins, ...) Pairz(ins), Pairs_54(__VA_ARGS__)
#define Pairs_56(ins, ...) Pairz(ins), Pairs_55(__VA_ARGS__)
#define Pairs_57(ins, ...) Pairz(ins), Pairs_56(__VA_ARGS__)
#define Pairs_58(ins, ...) Pairz(ins), Pairs_57(__VA_ARGS__)
#define Pairs_59(ins, ...) Pairz(ins), Pairs_58(__VA_ARGS__)
#define Pairs_60(ins, ...) Pairz(ins), Pairs_59(__VA_ARGS__)
#define Pairs_61(ins, ...) Pairz(ins), Pairs_60(__VA_ARGS__)
#define Pairs_62(ins, ...) Pairz(ins), Pairs_61(__VA_ARGS__)
#define Pairs_63(ins, ...) Pairz(ins), Pairs_62(__VA_ARGS__)
#define Pairs_64(ins, ...) Pairz(ins), Pairs_63(__VA_ARGS__)
#define Pairs_65(ins, ...) Pairz(ins), Pairs_64(__VA_ARGS__)
#define Pairs_66(ins, ...) Pairz(ins), Pairs_65(__VA_ARGS__)
#define Pairs_67(ins, ...) Pairz(ins), Pairs_66(__VA_ARGS__)
#define Pairs_68(ins, ...) Pairz(ins), Pairs_67(__VA_ARGS__)
#define Pairs_69(ins, ...) Pairz(ins), Pairs_68(__VA_ARGS__)
#define Pairs_70(ins, ...) Pairz(ins), Pairs_69(__VA_ARGS__)
#define Pairs_71(ins, ...) Pairz(ins), Pairs_70(__VA_ARGS__)
#define Pairs_72(ins, ...) Pairz(ins), Pairs_71(__VA_ARGS__)
#define Pairs_73(ins, ...) Pairz(ins), Pairs_72(__VA_ARGS__)
#define Pairs_74(ins, ...) Pairz(ins), Pairs_73(__VA_ARGS__)
#define Pairs_75(ins, ...) Pairz(ins), Pairs_74(__VA_ARGS__)
#define Pairs_76(ins, ...) Pairz(ins), Pairs_75(__VA_ARGS__)
#define Pairs_77(ins, ...) Pairz(ins), Pairs_76(__VA_ARGS__)
#define Pairs_78(ins, ...) Pairz(ins), Pairs_77(__VA_ARGS__)
#define Pairs_79(ins, ...) Pairz(ins), Pairs_78(__VA_ARGS__)
#define Pairs_80(ins, ...) Pairz(ins), Pairs_79(__VA_ARGS__)
#define Pairs_81(ins, ...) Pairz(ins), Pairs_80(__VA_ARGS__)
#define Pairs_82(ins, ...) Pairz(ins), Pairs_81(__VA_ARGS__)
#define Pairs_83(ins, ...) Pairz(ins), Pairs_82(__VA_ARGS__)
#define Pairs_84(ins, ...) Pairz(ins), Pairs_83(__VA_ARGS__)
#define Pairs_85(ins, ...) Pairz(ins), Pairs_84(__VA_ARGS__)
#define Pairs_86(ins, ...) Pairz(ins), Pairs_85(__VA_ARGS__)
#define Pairs_87(ins, ...) Pairz(ins), Pairs_86(__VA_ARGS__)
#define Pairs_88(ins, ...) Pairz(ins), Pairs_87(__VA_ARGS__)
#define Pairs_89(ins, ...) Pairz(ins), Pairs_88(__VA_ARGS__)
#define Pairs_90(ins, ...) Pairz(ins), Pairs_89(__VA_ARGS__)
#define Pairs_91(ins, ...) Pairz(ins), Pairs_90(__VA_ARGS__)
#define Pairs_92(ins, ...) Pairz(ins), Pairs_91(__VA_ARGS__)
#define Pairs_93(ins, ...) Pairz(ins), Pairs_92(__VA_ARGS__)
#define Pairs_94(ins, ...) Pairz(ins), Pairs_93(__VA_ARGS__)
#define Pairs_95(ins, ...) Pairz(ins), Pairs_94(__VA_ARGS__)
#define Pairs_96(ins, ...) Pairz(ins), Pairs_95(__VA_ARGS__)
#define Pairs_97(ins, ...) Pairz(ins), Pairs_96(__VA_ARGS__)
#define Pairs_98(ins, ...) Pairz(ins), Pairs_97(__VA_ARGS__)
#define Pairs_99(ins, ...) Pairz(ins), Pairs_98(__VA_ARGS__)
#define Pairs_100(ins, ...) Pairz(ins), Pairs_99(__VA_ARGS__)
#define Pairs_101(ins, ...) Pairz(ins), Pairs_100(__VA_ARGS__)
#define Pairs_102(ins, ...) Pairz(ins), Pairs_101(__VA_ARGS__)
#define Pairs_103(ins, ...) Pairz(ins), Pairs_102(__VA_ARGS__)
#define Pairs_104(ins, ...) Pairz(ins), Pairs_103(__VA_ARGS__)
#define Pairs_105(ins, ...) Pairz(ins), Pairs_104(__VA_ARGS__)
#define Pairs_106(ins, ...) Pairz(ins), Pairs_105(__VA_ARGS__)
#define Pairs_107(ins, ...) Pairz(ins), Pairs_106(__VA_ARGS__)
#define Pairs_108(ins, ...) Pairz(ins), Pairs_107(__VA_ARGS__)
#define Pairs_109(ins, ...) Pairz(ins), Pairs_108(__VA_ARGS__)
#define Pairs_110(ins, ...) Pairz(ins), Pairs_109(__VA_ARGS__)
#define Pairs_111(ins, ...) Pairz(ins), Pairs_110(__VA_ARGS__)
#define Pairs_112(ins, ...) Pairz(ins), Pairs_111(__VA_ARGS__)
#define Pairs_113(ins, ...) Pairz(ins), Pairs_112(__VA_ARGS__)
#define Pairs_114(ins, ...) Pairz(ins), Pairs_113(__VA_ARGS__)
#define Pairs_115(ins, ...) Pairz(ins), Pairs_114(__VA_ARGS__)
#define Pairs_116(ins, ...) Pairz(ins), Pairs_115(__VA_ARGS__)
#define Pairs_117(ins, ...) Pairz(ins), Pairs_116(__VA_ARGS__)
#define Pairs_118(ins, ...) Pairz(ins), Pairs_117(__VA_ARGS__)
#define Pairs_119(ins, ...) Pairz(ins), Pairs_118(__VA_ARGS__)
#define Pairs_120(ins, ...) Pairz(ins), Pairs_119(__VA_ARGS__)
#define Pairs_121(ins, ...) Pairz(ins), Pairs_120(__VA_ARGS__)
#define Pairs_122(ins, ...) Pairz(ins), Pairs_121(__VA_ARGS__)
#define Pairs_123(ins, ...) Pairz(ins), Pairs_122(__VA_ARGS__)
#define Pairs_124(ins, ...) Pairz(ins), Pairs_123(__VA_ARGS__)
#define Pairs_125(ins, ...) Pairz(ins), Pairs_124(__VA_ARGS__)
#define Pairs_126(ins, ...) Pairz(ins), Pairs_125(__VA_ARGS__)
#define Pairs_127(ins, ...) Pairz(ins), Pairs_126(__VA_ARGS__)
#define Pairs_128(ins, ...) Pairz(ins), Pairs_127(__VA_ARGS__)
#define Pairs_129(ins, ...) Pairz(ins), Pairs_128(__VA_ARGS__)
#define Pairs_130(ins, ...) Pairz(ins), Pairs_129(__VA_ARGS__)

#define MAKE_PAIRS(N, ...) PRIMITIVE_CAT(Pairs_, N)(__VA_ARGS__)

#define Pairs(...)                                                                                                                                             \
    { MAKE_PAIRS(_NARGS(__VA_ARGS__), __VA_ARGS__) }
#define Map(type, ...) map<string, type>(Pairs(__VA_ARGS__))
#define JSON(...) json(Pairs(__VA_ARGS__))
#define JSONStr(...) json(Pairs(__VA_ARGS__)).dump()

inline bool contains(json& j, string key) { return j.find(key) != j.end(); }

#define Pairx(ins) #ins, ins
#define Pairx_1(ins, ...) Pairx(ins)
#define Pairx_2(ins, ...) Pairx(ins), Pairx_1(__VA_ARGS__)
#define Pairx_3(ins, ...) Pairx(ins), Pairx_2(__VA_ARGS__)
#define Pairx_4(ins, ...) Pairx(ins), Pairx_3(__VA_ARGS__)
#define Pairx_5(ins, ...) Pairx(ins), Pairx_4(__VA_ARGS__)
#define Pairx_6(ins, ...) Pairx(ins), Pairx_5(__VA_ARGS__)
#define Pairx_7(ins, ...) Pairx(ins), Pairx_6(__VA_ARGS__)
#define Pairx_8(ins, ...) Pairx(ins), Pairx_7(__VA_ARGS__)
#define Pairx_9(ins, ...) Pairx(ins), Pairx_8(__VA_ARGS__)
#define Pairx_10(ins, ...) Pairx(ins), Pairx_9(__VA_ARGS__)
#define Pairx_11(ins, ...) Pairx(ins), Pairx_10(__VA_ARGS__)
#define Pairx_12(ins, ...) Pairx(ins), Pairx_11(__VA_ARGS__)
#define Pairx_13(ins, ...) Pairx(ins), Pairx_12(__VA_ARGS__)
#define Pairx_14(ins, ...) Pairx(ins), Pairx_13(__VA_ARGS__)
#define Pairx_15(ins, ...) Pairx(ins), Pairx_14(__VA_ARGS__)
#define Pairx_16(ins, ...) Pairx(ins), Pairx_15(__VA_ARGS__)
#define Pairx_17(ins, ...) Pairx(ins), Pairx_16(__VA_ARGS__)
#define Pairx_18(ins, ...) Pairx(ins), Pairx_17(__VA_ARGS__)
#define Pairx_19(ins, ...) Pairx(ins), Pairx_18(__VA_ARGS__)
#define Pairx_20(ins, ...) Pairx(ins), Pairx_19(__VA_ARGS__)
#define Pairx_21(ins, ...) Pairx(ins), Pairx_20(__VA_ARGS__)
#define Pairx_22(ins, ...) Pairx(ins), Pairx_21(__VA_ARGS__)
#define Pairx_23(ins, ...) Pairx(ins), Pairx_22(__VA_ARGS__)
#define Pairx_24(ins, ...) Pairx(ins), Pairx_23(__VA_ARGS__)
#define Pairx_25(ins, ...) Pairx(ins), Pairx_24(__VA_ARGS__)
#define Pairx_26(ins, ...) Pairx(ins), Pairx_25(__VA_ARGS__)
#define Pairx_27(ins, ...) Pairx(ins), Pairx_26(__VA_ARGS__)
#define Pairx_28(ins, ...) Pairx(ins), Pairx_27(__VA_ARGS__)
#define Pairx_29(ins, ...) Pairx(ins), Pairx_28(__VA_ARGS__)
#define Pairx_30(ins, ...) Pairx(ins), Pairx_29(__VA_ARGS__)
#define Pairx_31(ins, ...) Pairx(ins), Pairx_30(__VA_ARGS__)
#define Pairx_32(ins, ...) Pairx(ins), Pairx_31(__VA_ARGS__)
#define Pairx_33(ins, ...) Pairx(ins), Pairx_32(__VA_ARGS__)
#define Pairx_34(ins, ...) Pairx(ins), Pairx_33(__VA_ARGS__)
#define Pairx_35(ins, ...) Pairx(ins), Pairx_34(__VA_ARGS__)
#define Pairx_36(ins, ...) Pairx(ins), Pairx_35(__VA_ARGS__)
#define Pairx_37(ins, ...) Pairx(ins), Pairx_36(__VA_ARGS__)
#define Pairx_38(ins, ...) Pairx(ins), Pairx_37(__VA_ARGS__)
#define Pairx_39(ins, ...) Pairx(ins), Pairx_38(__VA_ARGS__)
#define Pairx_40(ins, ...) Pairx(ins), Pairx_39(__VA_ARGS__)
#define Pairx_41(ins, ...) Pairx(ins), Pairx_40(__VA_ARGS__)
#define Pairx_42(ins, ...) Pairx(ins), Pairx_41(__VA_ARGS__)
#define Pairx_43(ins, ...) Pairx(ins), Pairx_42(__VA_ARGS__)
#define Pairx_44(ins, ...) Pairx(ins), Pairx_43(__VA_ARGS__)
#define Pairx_45(ins, ...) Pairx(ins), Pairx_44(__VA_ARGS__)
#define Pairx_46(ins, ...) Pairx(ins), Pairx_45(__VA_ARGS__)
#define Pairx_47(ins, ...) Pairx(ins), Pairx_46(__VA_ARGS__)
#define Pairx_48(ins, ...) Pairx(ins), Pairx_47(__VA_ARGS__)
#define Pairx_49(ins, ...) Pairx(ins), Pairx_48(__VA_ARGS__)
#define Pairx_50(ins, ...) Pairx(ins), Pairx_49(__VA_ARGS__)
#define Pairx_51(ins, ...) Pairx(ins), Pairx_50(__VA_ARGS__)
#define Pairx_52(ins, ...) Pairx(ins), Pairx_51(__VA_ARGS__)
#define Pairx_53(ins, ...) Pairx(ins), Pairx_52(__VA_ARGS__)
#define Pairx_54(ins, ...) Pairx(ins), Pairx_53(__VA_ARGS__)
#define Pairx_55(ins, ...) Pairx(ins), Pairx_54(__VA_ARGS__)
#define Pairx_56(ins, ...) Pairx(ins), Pairx_55(__VA_ARGS__)
#define Pairx_57(ins, ...) Pairx(ins), Pairx_56(__VA_ARGS__)
#define Pairx_58(ins, ...) Pairx(ins), Pairx_57(__VA_ARGS__)
#define Pairx_59(ins, ...) Pairx(ins), Pairx_58(__VA_ARGS__)
#define Pairx_60(ins, ...) Pairx(ins), Pairx_59(__VA_ARGS__)
#define Pairx_61(ins, ...) Pairx(ins), Pairx_60(__VA_ARGS__)
#define Pairx_62(ins, ...) Pairx(ins), Pairx_61(__VA_ARGS__)
#define Pairx_63(ins, ...) Pairx(ins), Pairx_62(__VA_ARGS__)
#define Pairx_64(ins, ...) Pairx(ins), Pairx_63(__VA_ARGS__)
#define Pairx_65(ins, ...) Pairx(ins), Pairx_64(__VA_ARGS__)
#define Pairx_66(ins, ...) Pairx(ins), Pairx_65(__VA_ARGS__)
#define Pairx_67(ins, ...) Pairx(ins), Pairx_66(__VA_ARGS__)
#define Pairx_68(ins, ...) Pairx(ins), Pairx_67(__VA_ARGS__)
#define Pairx_69(ins, ...) Pairx(ins), Pairx_68(__VA_ARGS__)
#define Pairx_70(ins, ...) Pairx(ins), Pairx_69(__VA_ARGS__)
#define Pairx_71(ins, ...) Pairx(ins), Pairx_70(__VA_ARGS__)
#define Pairx_72(ins, ...) Pairx(ins), Pairx_71(__VA_ARGS__)
#define Pairx_73(ins, ...) Pairx(ins), Pairx_72(__VA_ARGS__)
#define Pairx_74(ins, ...) Pairx(ins), Pairx_73(__VA_ARGS__)
#define Pairx_75(ins, ...) Pairx(ins), Pairx_74(__VA_ARGS__)
#define Pairx_76(ins, ...) Pairx(ins), Pairx_75(__VA_ARGS__)
#define Pairx_77(ins, ...) Pairx(ins), Pairx_76(__VA_ARGS__)
#define Pairx_78(ins, ...) Pairx(ins), Pairx_77(__VA_ARGS__)
#define Pairx_79(ins, ...) Pairx(ins), Pairx_78(__VA_ARGS__)
#define Pairx_80(ins, ...) Pairx(ins), Pairx_79(__VA_ARGS__)
#define Pairx_81(ins, ...) Pairx(ins), Pairx_80(__VA_ARGS__)
#define Pairx_82(ins, ...) Pairx(ins), Pairx_81(__VA_ARGS__)
#define Pairx_83(ins, ...) Pairx(ins), Pairx_82(__VA_ARGS__)
#define Pairx_84(ins, ...) Pairx(ins), Pairx_83(__VA_ARGS__)
#define Pairx_85(ins, ...) Pairx(ins), Pairx_84(__VA_ARGS__)
#define Pairx_86(ins, ...) Pairx(ins), Pairx_85(__VA_ARGS__)
#define Pairx_87(ins, ...) Pairx(ins), Pairx_86(__VA_ARGS__)
#define Pairx_88(ins, ...) Pairx(ins), Pairx_87(__VA_ARGS__)
#define Pairx_89(ins, ...) Pairx(ins), Pairx_88(__VA_ARGS__)
#define Pairx_90(ins, ...) Pairx(ins), Pairx_89(__VA_ARGS__)
#define Pairx_91(ins, ...) Pairx(ins), Pairx_90(__VA_ARGS__)
#define Pairx_92(ins, ...) Pairx(ins), Pairx_91(__VA_ARGS__)
#define Pairx_93(ins, ...) Pairx(ins), Pairx_92(__VA_ARGS__)
#define Pairx_94(ins, ...) Pairx(ins), Pairx_93(__VA_ARGS__)
#define Pairx_95(ins, ...) Pairx(ins), Pairx_94(__VA_ARGS__)
#define Pairx_96(ins, ...) Pairx(ins), Pairx_95(__VA_ARGS__)
#define Pairx_97(ins, ...) Pairx(ins), Pairx_96(__VA_ARGS__)
#define Pairx_98(ins, ...) Pairx(ins), Pairx_97(__VA_ARGS__)
#define Pairx_99(ins, ...) Pairx(ins), Pairx_98(__VA_ARGS__)
#define Pairx_100(ins, ...) Pairx(ins), Pairx_99(__VA_ARGS__)
#define Pairx_101(ins, ...) Pairx(ins), Pairx_100(__VA_ARGS__)
#define Pairx_102(ins, ...) Pairx(ins), Pairx_101(__VA_ARGS__)
#define Pairx_103(ins, ...) Pairx(ins), Pairx_102(__VA_ARGS__)
#define Pairx_104(ins, ...) Pairx(ins), Pairx_103(__VA_ARGS__)
#define Pairx_105(ins, ...) Pairx(ins), Pairx_104(__VA_ARGS__)
#define Pairx_106(ins, ...) Pairx(ins), Pairx_105(__VA_ARGS__)
#define Pairx_107(ins, ...) Pairx(ins), Pairx_106(__VA_ARGS__)
#define Pairx_108(ins, ...) Pairx(ins), Pairx_107(__VA_ARGS__)
#define Pairx_109(ins, ...) Pairx(ins), Pairx_108(__VA_ARGS__)
#define Pairx_110(ins, ...) Pairx(ins), Pairx_109(__VA_ARGS__)
#define Pairx_111(ins, ...) Pairx(ins), Pairx_110(__VA_ARGS__)
#define Pairx_112(ins, ...) Pairx(ins), Pairx_111(__VA_ARGS__)
#define Pairx_113(ins, ...) Pairx(ins), Pairx_112(__VA_ARGS__)
#define Pairx_114(ins, ...) Pairx(ins), Pairx_113(__VA_ARGS__)
#define Pairx_115(ins, ...) Pairx(ins), Pairx_114(__VA_ARGS__)
#define Pairx_116(ins, ...) Pairx(ins), Pairx_115(__VA_ARGS__)
#define Pairx_117(ins, ...) Pairx(ins), Pairx_116(__VA_ARGS__)
#define Pairx_118(ins, ...) Pairx(ins), Pairx_117(__VA_ARGS__)
#define Pairx_119(ins, ...) Pairx(ins), Pairx_118(__VA_ARGS__)
#define Pairx_120(ins, ...) Pairx(ins), Pairx_119(__VA_ARGS__)
#define Pairx_121(ins, ...) Pairx(ins), Pairx_120(__VA_ARGS__)
#define Pairx_122(ins, ...) Pairx(ins), Pairx_121(__VA_ARGS__)
#define Pairx_123(ins, ...) Pairx(ins), Pairx_122(__VA_ARGS__)
#define Pairx_124(ins, ...) Pairx(ins), Pairx_123(__VA_ARGS__)
#define Pairx_125(ins, ...) Pairx(ins), Pairx_124(__VA_ARGS__)
#define Pairx_126(ins, ...) Pairx(ins), Pairx_125(__VA_ARGS__)
#define Pairx_127(ins, ...) Pairx(ins), Pairx_126(__VA_ARGS__)
#define Pairx_128(ins, ...) Pairx(ins), Pairx_127(__VA_ARGS__)
#define Pairx_129(ins, ...) Pairx(ins), Pairx_128(__VA_ARGS__)
#define Pairx_130(ins, ...) Pairx(ins), Pairx_129(__VA_ARGS__)

#define MAKE_PAIRX(N, ...) PRIMITIVE_CAT(Pairx_, N)(__VA_ARGS__)

template <typename T> void read_json_if_find(const json& j, const string& k, T& x) {
    auto it = j.find(k);
    if (it != j.end()) x = it->get<T>();
}
template <typename T> void read_json_if_find(const json& j, const string& k, vector<T>& x) {
    auto it = j.find(k);
    if (it != j.end()) x = it->get<vector<T>>();
}

// template <typename T> void read_json_if_find(const json& j, const string& k, vector<vector<T>>& x) {
//     auto it = j.find(k);
//     if (it != j.end()) x = it->get<vector<vector<T>>>();
// }

// template <typename T> void read_json_if_find(const json& j, const string& k, set<T>& x) {
//     auto it = j.find(k);
//     if (it != j.end()) x = it->get<set<T>>();
// }
template <typename T> void read_json_if_find(const json& j, string k) {
    (void)j;
    (void)k;
}
template <typename T> void read_json_if_find(const json& j) { (void)j; }
template <typename T, typename... ARGS> void read_json_if_find(const json& j, const string& k, T& x, ARGS&... args) {
    read_json_if_find(j, k, x);
    read_json_if_find(j, args...);
}

#define JRead(j, ...) read_json_if_find(j, MAKE_PAIRX(_NARGS(__VA_ARGS__), __VA_ARGS__));

#define ToJsonOut(...)                                                                                                                                         \
    json to_json() const override { return JSON(__VA_ARGS__); }
#define ToJsonIn(...)                                                                                                                                          \
    void assign(const json& j) override { JRead(j, __VA_ARGS__); };

#define ToJsonIO(...)                                                                                                                                          \
    ToJsonIn(__VA_ARGS__);                                                                                                                                     \
    ToJsonOut(__VA_ARGS__);

#define VirtualToJsonIO(...)                                                                                                                                   \
    virtual ToJsonIn(__VA_ARGS__);                                                                                                                             \
    virtual ToJsonOut(__VA_ARGS__);

#define assert_with(cond) for (; !(cond); assert(cond))

#endif